### ISSUE TITLE
Failed to apply plugin as "ERROR Could not translate your halconfig: Unrecognized field"

### ISSUE THREAD

**Issue by Mahito** [armory-plugins/armory-observability-plugin#21]
I tried armory-observability-plugin, but it didn’t work well.

```
$ hal deploy apply
- Get current deployment
  Failure
Validation in Global:
! ERROR Could not translate your halconfig: Unrecognized field
  "config.metrics" (class
  com.netflix.spinnaker.halyard.config.model.v1.plugins.Plugin), not marked as
  ignorable (5 known properties: "version", "enabled", "id", "extensions",
  "uiResourceLocation"])
at [Source: UNKNOWN; line: -1, column: -1] (through reference chain:
  com.netflix.spinnaker.halyard.config.model.v1.node.Halconfig["deploymentConfigurations"]->java.util.ArrayList[0]->com.netflix.spinnaker.halyard.config.model.v1.node.DeploymentConfiguration["spinnaker"]->com.netflix.spinnaker.halyard.config.model.v1.node.Spinnaker["extensibility"]->com.netflix.spinnaker.halyard.config.model.v1.node.Extensibility["plugins"]->java.util.LinkedHashMap["armory.observability-plugin"]->com.netflix.spinnaker.halyard.config.model.v1.plugins.Plugin["config.metrics"])
```

I think the config example in README is wrong because config.metrics must come under extensions as follow.
However, I couldn't find the value for extensions. (Ref: https://spinnaker.io/guides/user/plugins/)

- .hal/config
```
spinnaker:
  extensibility:
    plugins:
      Armory.ObservabilityPlugin:
        enabled: true
        extensions:
          Armory.observabilityPlugin:
            config.metrics:
              additionalTags:
              customerName: armory
              customerEnvName: production
            prometheus:
              enabled: true
              meterRegistryConfig.armoryRecommendedFiltersEnabled: true
```
